[program:pyvisioniq]
command=/opt/pyvisioniq/venv/bin/python /opt/pyvisioniq/pyvisioniq.py
directory=/opt/pyvisioniq
user=pyvisioniq
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/pyvisioniq/pyvisioniq.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
environment=PYVISIONIQ_MASTER_PASSWORD="%(ENV_PYVISIONIQ_MASTER_PASSWORD)s"